name: "Lint PR for valid release/version bump trigger"

on:
  pull_request_target:
    branches: [main]
    types: [assigned, opened, synchronize, reopened]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
